name: rtp
main: rtp\main
author: unknownguy2002
description: Random Woosh to nowhere
version: 1.1.1
api: [3.0.0]
website: unknown-dev.com
permissions:
 rtp:
  default: true
commands:
  rtp:
    description: "Teleport Players randomly"
    usage: "/rtp"



