name: rtp
main: rtp\main
author: Unknownguy2002
description: Random Woosh to nowhere
version: 1.0.0
api: [3.0.0]
website: unknown-dev.com
commands:
  rtp:
    description: "Teleport Players randomly"
    usage: "/rtp"



